"""Type stubs for the native Rust extension (rampa._core)."""

def rust_info() -> str: ...

class HdrHistogram:
    def __init__(self, sigfig: int = 3) -> None: ...
    def record(self, value: int) -> None: ...
    def record_n(self, value: int, count: int) -> None: ...
    def percentile(self, p: float) -> int: ...
    def mean(self) -> float: ...
    def min(self) -> int: ...
    def max(self) -> int: ...
    def count(self) -> int: ...
    def stdev(self) -> float: ...
    def reset(self) -> None: ...
    def format_stats(
        self,
    ) -> tuple[int, float, int, int, int, int, int, int]: ...
